# Generated by Django 2.2.5 on 2020-09-30 06:27

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMDB',
            fields=[
                ('name_director', models.CharField(default='0000000', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=50)),
                ('imdb_score', models.FloatField()),
                ('popularity_99', models.FloatField()),
                ('genre', django_mysql.models.ListTextField(models.CharField(max_length=25), size=50)),
            ],
        ),
    ]
